-- TAI TIME PHASE 2 KST cutover. EXECUTE = 0.
-- Generated by scripts/generate_time_kst_migration.py. Do not hand-edit ALTER list.
-- TAI Supabase vwlahtguyggrhvslabax: DO NOT RUN.

BEGIN;
-- 5 view DROP (pg_depend on ALTER source columns; explicit; CASCADE 금지)
DROP VIEW public.v_demo_buildings;
DROP VIEW public.v_equipment_unified;
DROP VIEW public.v_files_unified;
DROP VIEW public.v_payments_list;
DROP VIEW public.v_process_unified;
-- 237 column ALTER to timestamp without time zone (USING AT TIME ZONE Asia/Seoul)
ALTER TABLE public.accident_master ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.api_permissions ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.areas ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.areas ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.asset_template_map ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.attachments ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.attachments ALTER COLUMN taken_at TYPE timestamp without time zone USING taken_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.audit_logs ALTER COLUMN changed_at TYPE timestamp without time zone USING changed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.base_audit_fields ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.base_audit_fields ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.buildings ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.buildings ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.calendar_days ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.calendar_days ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.calendar_holidays ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.calendar_holidays ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.companies ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.companies ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.company_contacts ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.company_contacts ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.company_files ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.company_files ALTER COLUMN uploaded_at TYPE timestamp without time zone USING uploaded_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.construction_workers ALTER COLUMN signature_registered_at TYPE timestamp without time zone USING signature_registered_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.contracts ALTER COLUMN cancelled_at TYPE timestamp without time zone USING cancelled_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.contracts ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.contracts ALTER COLUMN paid_at TYPE timestamp without time zone USING paid_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.contracts ALTER COLUMN suspended_at TYPE timestamp without time zone USING suspended_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.contracts ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.corrective_actions ALTER COLUMN completed_at TYPE timestamp without time zone USING completed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.corrective_actions ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.corrective_actions ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.cron_job_log ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.cron_job_log ALTER COLUMN finished_at TYPE timestamp without time zone USING finished_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.cron_job_log ALTER COLUMN started_at TYPE timestamp without time zone USING started_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.cron_job_master ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.cron_job_master ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.cron_schedule_config ALTER COLUMN last_run_at TYPE timestamp without time zone USING last_run_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.cron_schedule_config ALTER COLUMN next_run_at TYPE timestamp without time zone USING next_run_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.cron_schedule_config ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.defect_notification_targets ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.defects ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.drawing_markers ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.education_files ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.education_files ALTER COLUMN uploaded_at TYPE timestamp without time zone USING uploaded_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.education_history ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.education_history ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.education_master ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.education_setting ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.education_setting ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.equipment_assets ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.equipment_assets ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.equipment_model_master ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.equipment_set_items ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.equipment_set_items ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.equipment_sets ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.equipment_sets ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.expert_applications ALTER COLUMN ai_review_at TYPE timestamp without time zone USING ai_review_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.expert_applications ALTER COLUMN approved_at TYPE timestamp without time zone USING approved_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.expert_applications ALTER COLUMN biz_verify_at TYPE timestamp without time zone USING biz_verify_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.expert_applications ALTER COLUMN legal_terms_agreed_at TYPE timestamp without time zone USING legal_terms_agreed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.facility_condition ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.facility_condition ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.facility_drawings ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.factories ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.factories ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.factory_contacts ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.factory_contacts ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.factory_features ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.failure_dictionary ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.failure_maintenance_inspection_map ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.failure_master ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.identity_logs ALTER COLUMN completed_at TYPE timestamp without time zone USING completed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.identity_logs ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.import_apply_logs ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.import_dataset_types ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.import_duplicate_checks ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.import_jobs ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.import_jobs ALTER COLUMN finished_at TYPE timestamp without time zone USING finished_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.import_jobs ALTER COLUMN started_at TYPE timestamp without time zone USING started_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.import_logs ALTER COLUMN uploaded_at TYPE timestamp without time zone USING uploaded_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.import_mapping_rules ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.import_mapping_rules ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.import_source_types ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.import_transform_rules ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.industry_context_master ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.industry_master ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.inspection_master ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.inspection_recommendation_advanced ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.inspection_recommendation_engine ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.inspection_set_items ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.inspection_set_items ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.inspection_sets ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.inspection_sets ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.kcsc_process_master ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.kcsc_process_master ALTER COLUMN updated_at_kcsc TYPE timestamp without time zone USING updated_at_kcsc AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.kcsc_work_master ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.ksic_process_map ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_article ALTER COLUMN classified_at TYPE timestamp without time zone USING classified_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_article ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_article ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_article_diff ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_article_diff ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_article_part ALTER COLUMN classified_at TYPE timestamp without time zone USING classified_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_article_part ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_article_part ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_attachment ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_attachment ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_change_log ALTER COLUMN change_detected_date TYPE timestamp without time zone USING change_detected_date AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_change_log ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_change_log ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_collection_target ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_collection_target ALTER COLUMN last_collected_at TYPE timestamp without time zone USING last_collected_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_collection_target ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_content_raw ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_content_raw ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_inspection_map ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_item ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_item ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_master ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_master ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_paragraph ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_paragraph ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_rule_source_map ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_rule_source_map ALTER COLUMN reviewed_at TYPE timestamp without time zone USING reviewed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_rule_source_map ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_update_tracking ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_update_tracking ALTER COLUMN last_checked_at TYPE timestamp without time zone USING last_checked_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_update_tracking ALTER COLUMN next_check_at TYPE timestamp without time zone USING next_check_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_update_tracking ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_version ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.law_version ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.legal_applications ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.legal_applications ALTER COLUMN evaluated_at TYPE timestamp without time zone USING evaluated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.legal_applications ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.maintenance_master ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.master_dangerous_goods ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.master_fields ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.master_fields ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.master_highpressure_gas ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.master_legal_inspection_cycles ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.master_legal_inspection_cycles ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.master_legal_inspection_target ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.master_products_elec ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.master_products_elec ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.master_safety_certification ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.master_safety_manager_criteria ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_contracts ALTER COLUMN client_confirm_at TYPE timestamp without time zone USING client_confirm_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_contracts ALTER COLUMN client_signed_at TYPE timestamp without time zone USING client_signed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_contracts ALTER COLUMN completed_at TYPE timestamp without time zone USING completed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_contracts ALTER COLUMN expert_signed_at TYPE timestamp without time zone USING expert_signed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_contracts ALTER COLUMN generated_at TYPE timestamp without time zone USING generated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_contracts ALTER COLUMN paid_confirmed_at TYPE timestamp without time zone USING paid_confirmed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_contracts ALTER COLUMN settled_at TYPE timestamp without time zone USING settled_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_contracts ALTER COLUMN vbank_expires_at TYPE timestamp without time zone USING vbank_expires_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_requests ALTER COLUMN cancelled_at TYPE timestamp without time zone USING cancelled_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_requests ALTER COLUMN matched_at TYPE timestamp without time zone USING matched_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_requests ALTER COLUMN selected_at TYPE timestamp without time zone USING selected_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_results ALTER COLUMN notified_at TYPE timestamp without time zone USING notified_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_results ALTER COLUMN proposed_at TYPE timestamp without time zone USING proposed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_results ALTER COLUMN rejected_at TYPE timestamp without time zone USING rejected_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_results ALTER COLUMN selected_at TYPE timestamp without time zone USING selected_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.matching_results ALTER COLUMN viewed_at TYPE timestamp without time zone USING viewed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.model_failure_map ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.model_maintenance_map ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.notification_logs ALTER COLUMN sent_at TYPE timestamp without time zone USING sent_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.notification_settings ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.notification_settings ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.notifications ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.notifications ALTER COLUMN read_at TYPE timestamp without time zone USING read_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.notifications ALTER COLUMN sent_at TYPE timestamp without time zone USING sent_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.payments ALTER COLUMN cancelled_at TYPE timestamp without time zone USING cancelled_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.payments ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.payments ALTER COLUMN expired_at TYPE timestamp without time zone USING expired_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.payments ALTER COLUMN paid_at TYPE timestamp without time zone USING paid_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.payments ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.payments ALTER COLUMN vbank_confirmed_at TYPE timestamp without time zone USING vbank_confirmed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.payments ALTER COLUMN vbank_expires_at TYPE timestamp without time zone USING vbank_expires_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.permission_groups ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.permissions ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.price_change_log ALTER COLUMN changed_at TYPE timestamp without time zone USING changed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.price_commission ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.price_commission ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.price_consulting ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.price_consulting ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.price_repair_brokerage ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.price_repair_brokerage ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.price_safety_management ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.price_safety_management ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.process_equipment_map ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.processed_import_rows ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.processed_import_rows ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.processed_validation_results ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.qr_entities ALTER COLUMN issued_at TYPE timestamp without time zone USING issued_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.quotes ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.quotes ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.raw_import_batches ALTER COLUMN processed_at TYPE timestamp without time zone USING processed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.raw_import_batches ALTER COLUMN uploaded_at TYPE timestamp without time zone USING uploaded_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.raw_import_errors ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.raw_import_rows ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.repair_cost_map ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.replacement_prediction_engine ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.risk_score_engine ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.risk_score_engine_advanced ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.role_data_scope ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.role_menu_permissions ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.role_permissions ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.roles ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.roles ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.safety_inspection_results ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.safety_inspections ALTER COLUMN inspection_date TYPE timestamp without time zone USING inspection_date AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.schedule_logs ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.semantic_clause_relation ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.settlements ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.settlements ALTER COLUMN invoice_issued_at TYPE timestamp without time zone USING invoice_issued_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.settlements ALTER COLUMN settled_at TYPE timestamp without time zone USING settled_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.settlements ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.site_equipment_set_items ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.site_equipment_set_items ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.site_equipment_sets ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.site_equipment_sets ALTER COLUMN reviewed_at TYPE timestamp without time zone USING reviewed_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.site_equipment_sets ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.sites ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.system_codes ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.system_codes ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.task_master ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.tbm_meetings ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.tbm_meetings ALTER COLUMN meeting_date TYPE timestamp without time zone USING meeting_date AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.tbm_meetings ALTER COLUMN qr_expires_at TYPE timestamp without time zone USING qr_expires_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.teams ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.teams ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.users ALTER COLUMN biometric_at TYPE timestamp without time zone USING biometric_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.users ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.users ALTER COLUMN last_login_at TYPE timestamp without time zone USING last_login_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.users ALTER COLUMN signature_registered_at TYPE timestamp without time zone USING signature_registered_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.users ALTER COLUMN updated_at TYPE timestamp without time zone USING updated_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.work_assignments ALTER COLUMN created_at TYPE timestamp without time zone USING created_at AT TIME ZONE 'Asia/Seoul';
ALTER TABLE public.work_schedules ALTER COLUMN reviewed_at TYPE timestamp without time zone USING reviewed_at AT TIME ZONE 'Asia/Seoul';
-- 5 view EXACT recreate + OWNER / GRANT ALL / COMMENT (omit COMMENT when null)
CREATE VIEW public.v_demo_buildings AS
SELECT f.id, f.name AS factory_name, f.main_purpose_name, f.building_area, f.floor_count, f.is_multi_use, f.occupant_capacity, f.status_code, f.remarks, f.address_sido, f.address_sigungu, c.name AS company_name, c.business_number, dr.rule_count, dr.diagnosis_stage, f.created_at
   FROM factories f LEFT JOIN companies c ON c.id = f.company_id
     LEFT JOIN factory_diagnosis_results dr ON dr.factory_id = f.id AND dr.is_latest = true
  WHERE f.sector::text = 'BUILDING'::text AND f.remarks ~~ '%SEED_BUILDING_v1%'::text;
CREATE VIEW public.v_equipment_unified AS
SELECT DISTINCT ON (industry_code_full, process_id, facility_name_std) id, industry_code_full, industry_name_full, process_id, process_path, facility_name_std, match_band, match_score, match_basis, source_type, equipment_source_file, process_source,
    CASE source_type WHEN 'KOSHA_GUIDE'::text THEN 1 WHEN 'KOSHA_GUIDE_V2'::text THEN 1 WHEN 'EXISTING_FINAL'::text THEN 2 WHEN 'SYNTHETIC_PRIORITY'::text THEN 3 WHEN 'ENHANCED_ADDED'::text THEN 4 WHEN 'EXISTING_FILL'::text THEN 5 ELSE 6 END AS source_priority, created_at
   FROM process_equipment_map
  ORDER BY industry_code_full, process_id, facility_name_std, (CASE source_type WHEN 'KOSHA_GUIDE'::text THEN 1 WHEN 'KOSHA_GUIDE_V2'::text THEN 1 WHEN 'EXISTING_FINAL'::text THEN 2 WHEN 'SYNTHETIC_PRIORITY'::text THEN 3 WHEN 'ENHANCED_ADDED'::text THEN 4 WHEN 'EXISTING_FILL'::text THEN 5 ELSE 6 END);
CREATE VIEW public.v_files_unified AS
SELECT d.id::text AS id,
    'documents'::text AS source,
    d.company_id,
    d.factory_id,
    d.file_name,
    COALESCE(d.storage_path, ''::text) AS file_ref,
    d.category::text AS category,
        CASE
            WHEN d.deleted_at IS NOT NULL THEN 'DELETED'::text
            WHEN d.is_active = false THEN 'INACTIVE'::text
            ELSE 'ACTIVE'::text
        END AS status,
    d.file_size,
    d.uploaded_at AS created_at
   FROM documents d
UNION ALL
 SELECT cf.id::text AS id,
    'company_files'::text AS source,
    cf.company_id,
    NULL::uuid AS factory_id,
    cf.file_name,
    COALESCE(cf.file_url, ''::text) AS file_ref,
    cf.file_type AS category,
        CASE
            WHEN cf.is_active = false THEN 'INACTIVE'::text
            ELSE 'ACTIVE'::text
        END AS status,
    cf.file_size,
    cf.uploaded_at AS created_at
   FROM company_files cf
UNION ALL
 SELECT gd.id::text AS id,
    'generated_document'::text AS source,
    f.company_id,
    gd.factory_id,
    gd.document_name AS file_name,
    COALESCE(gd.download_url, gd.storage_path, ''::text) AS file_ref,
    gd.form_code AS category,
    gd.status,
    NULL::integer AS file_size,
    gd.created_at
   FROM generated_document gd
     LEFT JOIN factories f ON f.id = gd.factory_id;
CREATE VIEW public.v_payments_list AS
SELECT p.id, p.user_id, p.company_id, p.contract_id, p.product_type, p.plan_code, p.period_months, p.total_amount, p.supply_amount, p.vat_amount, p.pg_method, p.payment_method, p.payment_type, p.status_code, p.service_status, p.paid_at, p.expired_at, p.cancelled_at, p.cancel_reason, p.fail_reason, p.inicis_order_id, p.inicis_auth_code, p.inicis_tid, p.inicis_card_name, p.memo, p.created_at, p.updated_at, u.name AS user_name, u.email AS user_email, u.phone AS user_phone, c.name AS company_name, c.business_number AS company_biz_no, c.phone AS company_phone
   FROM payments p
     LEFT JOIN users u ON u.id = p.user_id
     LEFT JOIN companies c ON c.id = COALESCE(p.company_id, u.company_id);
CREATE VIEW public.v_process_unified AS
SELECT DISTINCT ON (industry_code_full, process_path) id, industry_code_full, industry_name_full, process_id, process_lv1, process_lv2, process_lv3, process_lv4, process_path, mapping_basis, process_source, template_source,
    CASE process_source WHEN 'KOSHA_GUIDE'::text THEN 1 WHEN 'KOSHA_GUIDE_V2'::text THEN 1 WHEN 'TAI_EXISTING'::text THEN 2 WHEN 'TEMPLATE'::text THEN 3 ELSE 4 END AS source_priority, created_at
   FROM ksic_process_map
  ORDER BY industry_code_full, process_path, (CASE process_source WHEN 'KOSHA_GUIDE'::text THEN 1 WHEN 'KOSHA_GUIDE_V2'::text THEN 1 WHEN 'TAI_EXISTING'::text THEN 2 WHEN 'TEMPLATE'::text THEN 3 ELSE 4 END);
ALTER VIEW public.v_demo_buildings OWNER TO postgres;
ALTER VIEW public.v_equipment_unified OWNER TO postgres;
ALTER VIEW public.v_files_unified OWNER TO postgres;
ALTER VIEW public.v_payments_list OWNER TO postgres;
ALTER VIEW public.v_process_unified OWNER TO postgres;
GRANT ALL ON TABLE public.v_demo_buildings TO anon;
GRANT ALL ON TABLE public.v_demo_buildings TO authenticated;
GRANT ALL ON TABLE public.v_demo_buildings TO postgres;
GRANT ALL ON TABLE public.v_demo_buildings TO service_role;
GRANT ALL ON TABLE public.v_equipment_unified TO anon;
GRANT ALL ON TABLE public.v_equipment_unified TO authenticated;
GRANT ALL ON TABLE public.v_equipment_unified TO postgres;
GRANT ALL ON TABLE public.v_equipment_unified TO service_role;
GRANT ALL ON TABLE public.v_files_unified TO anon;
GRANT ALL ON TABLE public.v_files_unified TO authenticated;
GRANT ALL ON TABLE public.v_files_unified TO postgres;
GRANT ALL ON TABLE public.v_files_unified TO service_role;
GRANT ALL ON TABLE public.v_payments_list TO anon;
GRANT ALL ON TABLE public.v_payments_list TO authenticated;
GRANT ALL ON TABLE public.v_payments_list TO postgres;
GRANT ALL ON TABLE public.v_payments_list TO service_role;
GRANT ALL ON TABLE public.v_process_unified TO anon;
GRANT ALL ON TABLE public.v_process_unified TO authenticated;
GRANT ALL ON TABLE public.v_process_unified TO postgres;
GRANT ALL ON TABLE public.v_process_unified TO service_role;
COMMENT ON VIEW public.v_equipment_unified IS '통합 설비 뷰 - KOSHA_GUIDE > EXISTING_FINAL > SYNTHETIC > ENHANCED 우선순위로 중복 제거';
COMMENT ON VIEW public.v_files_unified IS 'WO-9 파일 통합뷰: documents+company_files+generated_document(factory→company). 읽기 전용, company_id 축.';
COMMENT ON VIEW public.v_process_unified IS '통합 공정 뷰 - KOSHA_GUIDE > TAI_EXISTING > TEMPLATE 우선순위로 process_path 중복 제거';
COMMIT;
