-- WO-SAFETY-LIBRARY-001 WP-1C-5B PATCH-5B-HOLD
-- Additive OPEN/RESOLVED hold ledger for source-resolution data-quality exceptions.
-- Does not alter catalog / snapshots / details / assets / asset_versions.
-- service_role only. No anon/authenticated policies. No DELETE grant.

CREATE TABLE IF NOT EXISTS public.kosha_safety_material_storage_holds (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id            bigint NOT NULL REFERENCES public.kosha_safety_material_assets(id) ON DELETE RESTRICT,
    material_id         text NOT NULL REFERENCES public.kosha_safety_materials(id) ON DELETE RESTRICT,
    snapshot_id         uuid NOT NULL REFERENCES public.kosha_safety_material_snapshots(id) ON DELETE RESTRICT,
    source_med_seq      text,
    reason              text NOT NULL,
    expected_file_name  text,
    observed_files      jsonb NOT NULL DEFAULT '[]'::jsonb,
    observed_at         timestamptz NOT NULL DEFAULT now(),
    status              text NOT NULL DEFAULT 'OPEN',
    resolution_note     text,
    resolved_at         timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT kosha_safety_material_storage_holds_reason_check
        CHECK (reason IN (
            'SOURCE_ASSET_FILENAME_MISMATCH',
            'SOURCE_ASSET_ZERO_MATCH',
            'SOURCE_ASSET_MULTI_MATCH'
        )),
    CONSTRAINT kosha_safety_material_storage_holds_status_check
        CHECK (status IN ('OPEN', 'RESOLVED')),
    CONSTRAINT kosha_safety_material_storage_holds_snapshot_asset_reason_uidx
        UNIQUE (snapshot_id, asset_id, reason)
);

CREATE INDEX IF NOT EXISTS kosha_safety_material_storage_holds_open_idx
    ON public.kosha_safety_material_storage_holds (snapshot_id, status, asset_id);

ALTER TABLE public.kosha_safety_material_storage_holds ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.kosha_safety_material_storage_holds FROM PUBLIC;
REVOKE ALL ON TABLE public.kosha_safety_material_storage_holds FROM anon;
REVOKE ALL ON TABLE public.kosha_safety_material_storage_holds FROM authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.kosha_safety_material_storage_holds TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.kosha_safety_material_storage_holds_id_seq TO service_role;
