-- WO-SAFETY-LIBRARY-001 WP-1C-4A
-- Current official KOSHA safety-material snapshot SoT.
-- Additive only. kosha_safety_materials 컬럼을 변경하지 않는다.
-- service_role 작업용. 이번 WP에서 anon/authenticated/public write·공개 SELECT policy 없음.

CREATE TABLE IF NOT EXISTS kosha_safety_material_snapshots (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    source_provider     text NOT NULL DEFAULT 'KOSHA',
    source_dataset      text NOT NULL,
    source_call_api_id  text NOT NULL,
    started_at          timestamptz NOT NULL,
    completed_at        timestamptz,
    declared_total      integer,
    fetched_count       integer,
    unique_count        integer,
    duplicate_count     integer,
    invalid_count       integer,
    snapshot_hash       text,
    status              text NOT NULL,
    failure_reason      text,
    created_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT kosha_safety_material_snapshots_status_check
        CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS kosha_safety_material_snapshots_status_completed_idx
    ON kosha_safety_material_snapshots (status, completed_at DESC);

CREATE INDEX IF NOT EXISTS kosha_safety_material_snapshots_hash_idx
    ON kosha_safety_material_snapshots (snapshot_hash);

CREATE TABLE IF NOT EXISTS kosha_safety_material_snapshot_items (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id             uuid NOT NULL REFERENCES kosha_safety_material_snapshots(id),
    material_id             text NOT NULL REFERENCES kosha_safety_materials(id),
    source_med_seq          text NOT NULL,
    source_url              text NOT NULL,
    source_title            text NOT NULL,
    source_published_date   date,
    observed_at             timestamptz NOT NULL,
    created_at              timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT kosha_safety_material_snapshot_items_snapshot_material_uidx
        UNIQUE (snapshot_id, material_id),
    CONSTRAINT kosha_safety_material_snapshot_items_snapshot_medseq_uidx
        UNIQUE (snapshot_id, source_med_seq)
);

CREATE INDEX IF NOT EXISTS kosha_safety_material_snapshot_items_snapshot_idx
    ON kosha_safety_material_snapshot_items (snapshot_id);

CREATE INDEX IF NOT EXISTS kosha_safety_material_snapshot_items_material_idx
    ON kosha_safety_material_snapshot_items (material_id);

ALTER TABLE kosha_safety_material_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE kosha_safety_material_snapshot_items ENABLE ROW LEVEL SECURITY;
