"""External & Communication — 외부API·메시징·매칭·어드민 라우터."""
ROUTERS = [
    {"module": "routers.weather"},
    {"module": "routers.juso"},
    {"module": "routers.building_register", "prefix": "/building-register"},
    {"module": "routers.biz_verify"},
    {"module": "routers.kosha_apis"},
    {"module": "routers.messaging"},
    {"module": "routers.fcm"},
    {"module": "routers.mail"},
    {"module": "routers.ai_copywrite"},
    {"module": "routers.event_trigger"},
    {"module": "routers.repair"},
    {"module": "routers.fix_chat"},
    {"module": "routers.fix_providers_api"},
    {"module": "routers.matching", "prefix": "/matching", "tags": ["매칭"]},
    {"module": "routers.matching_commission", "attr": "commission_router", "prefix": "/price-commission", "tags": ["수수료설정"]},
    {"module": "routers.experts", "prefix": "/experts", "tags": ["전문가"]},
    {"module": "routers.identity", "prefix": "/identity", "tags": ["본인인증"]},
    {"module": "routers.identity_test"},
    {"module": "routers.agent_service"},
    {"module": "routers.admin_review"},
    {"module": "routers.admin_stats"},
    {"module": "routers.cron_manager"},
    {"module": "routers.internal_api_registry"},
    {"module": "routers.report_api_registry"},
    {"module": "routers.fire_hazmat"},
    {"module": "routers.precedent_api"},
    {"module": "routers.contract_kmong"},
    {"module": "routers.watch_engine_api"},
    {"module": "routers.watch_engine_alert_api"},
    {"module": "routers.watch_engine_browser_api"},
    {"module": "routers.watch_engine_sla_api"},
    {"module": "routers.watch_engine_incident_api"},
    {"module": "routers.watch_engine_recovery_api"},
    {"module": "routers.watch_engine_knowledge_api"},
    {"module": "routers.watch_engine_memory_api"},
    {"module": "routers.watch_engine_governance_api"},
    {"module": "routers.watch_engine_identity_api"},
    {"module": "routers.watch_engine_control_api"},
    {"module": "routers.watch_engine_document_api"},
    {"module": "routers.watch_engine_intelligence_api"},
    {"module": "routers.pricing_validation_api"},
    {"module": "routers.payment_activation_api"},
    {"module": "routers.semantic_adapter_api"},
    {"module": "routers.production_guard_api"},
    {"module": "routers.control_runtime_gateway_api"},
    {"module": "routers.synthetic_control_api"},
    {"module": "routers.calibration_api"},
    {"module": "routers.feedback_api"},
    {"module": "routers.trans_engine_api"},
    {"module": "routers.situation_history_api"},
    {"module": "routers.situation_dashboard_api"},
    {"module": "routers.attention_dashboard_api"},
    {"module": "routers.response_guidance_api"},
]
