"""External & Communication — 외부API·메시징·매칭·어드민 라우터."""
ROUTERS = [
    {"module": "routers.weather"},
    {"module": "routers.juso"},
    {"module": "routers.building_register", "prefix": "/building-register"},
    {"module": "routers.biz_verify"},
    {"module": "routers.kosha_apis"},
    {"module": "routers.messaging"},
    {"module": "routers.fcm"},
    {"module": "routers.mail"},
    {"module": "routers.ai_copywrite"},
    {"module": "routers.event_trigger"},
    {"module": "routers.repair"},
    {"module": "routers.fix_chat"},
    {"module": "routers.fix_providers_api"},
    {"module": "routers.matching", "prefix": "/matching", "tags": ["매칭"]},
    {"module": "routers.matching_commission", "attr": "commission_router", "prefix": "/price-commission", "tags": ["수수료설정"]},
    {"module": "routers.experts", "prefix": "/experts", "tags": ["전문가"]},
    {"module": "routers.identity", "prefix": "/identity", "tags": ["본인인증"]},
    {"module": "routers.agent_service"},
    {"module": "routers.admin_review"},
    {"module": "routers.admin_stats"},
    {"module": "routers.cron_manager"},
    {"module": "routers.internal_api_registry"},
    {"module": "routers.report_api_registry"},
    {"module": "routers.fire_hazmat"},
    {"module": "routers.precedent_api"},
    {"module": "routers.contract_kmong"},
    {"module": "routers.watch_engine_api"},
    {"module": "routers.watch_engine_alert_api"},
    {"module": "routers.watch_engine_browser_api"},
    {"module": "routers.watch_engine_sla_api"},
    {"module": "routers.watch_engine_incident_api"},
]
