"""
Registry of 118 XLSX_BUILD targets — WO-REF01-XLS03-BULK-XLSX-BUILD-001.
Auto-generated from XLS02-189-FINAL-SCOPE.csv.
"""

REGISTRY: dict[str, dict] = {
    "CHW-01": {
        "source_title": "화학물질 입고·검수 기록표",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-CHW-01.xlsx",
        "forbidden_formula": False,
    },
    "CHW-02": {
        "source_title": "화학물질 출고·사용 불출대장",
        "design_type": "CALC_AGG",
        "output_filename": "TAI-FORM-CHW-02.xlsx",
        "forbidden_formula": False,
    },
    "CHW-03": {
        "source_title": "화학물질 재고실사·차이처리표",
        "design_type": "CALC_AGG",
        "output_filename": "TAI-FORM-CHW-03.xlsx",
        "forbidden_formula": True,
    },
    "CHW-04": {
        "source_title": "화학물질 이상품 격리·처리 기록",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-CHW-04.xlsx",
        "forbidden_formula": False,
    },
    "CITYGAS-01": {
        "source_title": "도시가스 공급·사용시설 안전점검 기록표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-CITYGAS-01.xlsx",
        "forbidden_formula": False,
    },
    "CONF-02": {
        "source_title": "밀폐공간 산소·유해가스 측정 기록부",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-CONF-02.xlsx",
        "forbidden_formula": False,
    },
    "CONF-03": {
        "source_title": "밀폐공간 출입·감시 기록부",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-CONF-03.xlsx",
        "forbidden_formula": False,
    },
    "CONF-04": {
        "source_title": "밀폐공간 비상구조 장비 점검표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-CONF-04.xlsx",
        "forbidden_formula": False,
    },
    "DOC-01": {
        "source_title": "안전관리 문서 개정·승인 이력대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-DOC-01.xlsx",
        "forbidden_formula": False,
    },
    "DOC-02": {
        "source_title": "안전관리 서식 배포·회수 관리대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-DOC-02.xlsx",
        "forbidden_formula": False,
    },
    "DOC-03": {
        "source_title": "안전관리 기록물 보존·폐기 일정표",
        "design_type": "DATE_STATUS",
        "output_filename": "TAI-FORM-DOC-03.xlsx",
        "forbidden_formula": False,
    },
    "ENV-01": {
        "source_title": "대기배출시설·방지시설 자체관리 점검표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-ENV-01.xlsx",
        "forbidden_formula": False,
    },
    "ENV-02": {
        "source_title": "폐수처리시설 점검 및 개선관리대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-ENV-02.xlsx",
        "forbidden_formula": False,
    },
    "ENV-03": {
        "source_title": "폐기물 보관장소 일상점검표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-ENV-03.xlsx",
        "forbidden_formula": False,
    },
    "ENV-04": {
        "source_title": "환경설비 정기보전·수리 기록부",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-ENV-04.xlsx",
        "forbidden_formula": False,
    },
    "EQUIP-01": {
        "source_title": "지게차 작업계획서",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-EQUIP-01.xlsx",
        "forbidden_formula": False,
    },
    "EQUIP-02": {
        "source_title": "트럭 적재·운반 작업계획서",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-EQUIP-02.xlsx",
        "forbidden_formula": False,
    },
    "EQUIP-03": {
        "source_title": "고소작업대 작업계획서",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-EQUIP-03.xlsx",
        "forbidden_formula": False,
    },
    "EQUIP-04": {
        "source_title": "이동식크레인 작업계획서",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-EQUIP-04.xlsx",
        "forbidden_formula": False,
    },
    "EQUIP-05": {
        "source_title": "굴착기 작업계획서",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-EQUIP-05.xlsx",
        "forbidden_formula": False,
    },
    "EQUIP-06": {
        "source_title": "지게차 안전점검표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-EQUIP-06.xlsx",
        "forbidden_formula": False,
    },
    "EQUIP-07": {
        "source_title": "크레인 안전점검표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-EQUIP-07.xlsx",
        "forbidden_formula": False,
    },
    "EQUIP-08": {
        "source_title": "컨베이어 자율점검표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-EQUIP-08.xlsx",
        "forbidden_formula": False,
    },
    "GOV-01": {
        "source_title": "산업안전보건위원회 회의록",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-GOV-01.xlsx",
        "forbidden_formula": False,
    },
    "GOV-02": {
        "source_title": "산업안전보건위원회 의결사항 이행관리대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-GOV-02.xlsx",
        "forbidden_formula": False,
    },
    "GOV-03": {
        "source_title": "근로자 안전보건 의견수렴·회신대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-GOV-03.xlsx",
        "forbidden_formula": False,
    },
    "GOV-04": {
        "source_title": "관리감독자 현장 안전활동 기록지",
        "design_type": "DAILY_LOG",
        "output_filename": "TAI-FORM-GOV-04.xlsx",
        "forbidden_formula": False,
    },
    "GOV-05": {
        "source_title": "관리감독자 업무수행 평가표",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-GOV-05.xlsx",
        "forbidden_formula": False,
    },
    "GOV-06": {
        "source_title": "안전보건협의체 회의록(도급사업)",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-GOV-06.xlsx",
        "forbidden_formula": False,
    },
    "GOV-07": {
        "source_title": "합동안전보건점검 및 시정조치 기록",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-GOV-07.xlsx",
        "forbidden_formula": False,
    },
    "GOV-09": {
        "source_title": "안전보건 시정조치(CAPA) 관리대장",
        "design_type": "CALC_AGG",
        "output_filename": "TAI-FORM-GOV-09.xlsx",
        "forbidden_formula": False,
    },
    "GOV-10": {
        "source_title": "안전보건 연간 활동계획·실적 대비표",
        "design_type": "CALC_AGG",
        "output_filename": "TAI-FORM-GOV-10.xlsx",
        "forbidden_formula": False,
    },
    "GOV-11": {
        "source_title": "안전보건 내부점검 결과보고서",
        "design_type": "PLAN_EVAL",
        "output_filename": "TAI-FORM-GOV-11.xlsx",
        "forbidden_formula": False,
    },
    "H2-01": {
        "source_title": "수소설비 운전·점검 기록부",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-H2-01.xlsx",
        "forbidden_formula": False,
    },
    "H2-02": {
        "source_title": "수소누출 대응 훈련기록표",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-H2-02.xlsx",
        "forbidden_formula": False,
    },
    "HAZ-01": {
        "source_title": "위험물 저장·취급시설 관리점검표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-HAZ-01.xlsx",
        "forbidden_formula": False,
    },
    "LAB-01": {
        "source_title": "연구실 일상 안전점검 기록표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-LAB-01.xlsx",
        "forbidden_formula": False,
    },
    "LAB-02": {
        "source_title": "연구실 정밀안전진단 개선조치 대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-LAB-02.xlsx",
        "forbidden_formula": False,
    },
    "LPG-01": {
        "source_title": "LPG 사용시설 안전점검 기록표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-LPG-01.xlsx",
        "forbidden_formula": False,
    },
    "MNT-03": {
        "source_title": "설비보전 작업일지",
        "design_type": "DAILY_LOG",
        "output_filename": "TAI-FORM-MNT-03.xlsx",
        "forbidden_formula": False,
    },
    "P-01": {
        "source_title": "D-1 내일 작업계획·위험조율표",
        "design_type": "DAILY_LOG",
        "output_filename": "TAI-FORM-P-01.xlsx",
        "forbidden_formula": False,
    },
    "P-02": {
        "source_title": "일일 안전관리 업무일지",
        "design_type": "DAILY_LOG",
        "output_filename": "TAI-FORM-P-02.xlsx",
        "forbidden_formula": False,
    },
    "P-03": {
        "source_title": "현장 안전순찰·지도 일지",
        "design_type": "DAILY_LOG",
        "output_filename": "TAI-FORM-P-03.xlsx",
        "forbidden_formula": False,
    },
    "P-04": {
        "source_title": "TBM 실시 및 작업자 확인 기록",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-P-04.xlsx",
        "forbidden_formula": False,
    },
    "P-06": {
        "source_title": "통합 위험작업 허가관리대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-P-06.xlsx",
        "forbidden_formula": False,
    },
    "P-07": {
        "source_title": "위험작업 동시작업 간섭조정표",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-P-07.xlsx",
        "forbidden_formula": False,
    },
    "P-08": {
        "source_title": "중장비 반입 사전검토·승인서",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-P-08.xlsx",
        "forbidden_formula": False,
    },
    "P-09": {
        "source_title": "장비·운전원 자격·검사 만료관리표",
        "design_type": "DATE_STATUS",
        "output_filename": "TAI-FORM-P-09.xlsx",
        "forbidden_formula": False,
    },
    "P-10": {
        "source_title": "안전시설물 설치확인서",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-P-10.xlsx",
        "forbidden_formula": False,
    },
    "P-11": {
        "source_title": "가설시설·비계·거푸집 점검표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-P-11.xlsx",
        "forbidden_formula": False,
    },
    "P-12": {
        "source_title": "가설전기·임시배선 안전점검표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-P-12.xlsx",
        "forbidden_formula": False,
    },
    "P-13": {
        "source_title": "위험요인 지적·조치·재점검 대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-P-13.xlsx",
        "forbidden_formula": False,
    },
    "P-16": {
        "source_title": "신규작업자 투입 전 서류확인표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-P-16.xlsx",
        "forbidden_formula": False,
    },
    "P-17": {
        "source_title": "외국인·신규작업자 이해확인 기록",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-P-17.xlsx",
        "forbidden_formula": False,
    },
    "P-18": {
        "source_title": "협력업체 일일 작업·위험정보 공유표",
        "design_type": "DAILY_LOG",
        "output_filename": "TAI-FORM-P-18.xlsx",
        "forbidden_formula": False,
    },
    "P-19": {
        "source_title": "협력업체 투입 전 적격성·서류확인표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-P-19.xlsx",
        "forbidden_formula": False,
    },
    "P-20": {
        "source_title": "산업안전보건관리비 사용계획·집행내역",
        "design_type": "CALC_AGG",
        "output_filename": "TAI-FORM-P-20.xlsx",
        "forbidden_formula": False,
    },
    "P-21": {
        "source_title": "산업안전보건관리비 지출증빙 체크리스트",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-P-21.xlsx",
        "forbidden_formula": False,
    },
    "P-22": {
        "source_title": "월간 안전관리 업무캘린더",
        "design_type": "DATE_STATUS",
        "output_filename": "TAI-FORM-P-22.xlsx",
        "forbidden_formula": False,
    },
    "P-24": {
        "source_title": "현장 핵심문서·증빙 보유현황표",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-P-24.xlsx",
        "forbidden_formula": False,
    },
    "P-25": {
        "source_title": "주간 안전관리 실적·이슈 보고서",
        "design_type": "PLAN_EVAL",
        "output_filename": "TAI-FORM-P-25.xlsx",
        "forbidden_formula": False,
    },
    "P-26": {
        "source_title": "월간 안전보건 지표·경영보고서",
        "design_type": "CALC_AGG",
        "output_filename": "TAI-FORM-P-26.xlsx",
        "forbidden_formula": False,
    },
    "PRA-22-02": {
        "source_title": "화학물질 로케이션 적치·이동기록",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-PRA-22-02.xlsx",
        "forbidden_formula": False,
    },
    "PRA-22-09": {
        "source_title": "현장 안전점검 사진·증빙 인계목록",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-PRA-22-09.xlsx",
        "forbidden_formula": False,
    },
    "PRA-22-10": {
        "source_title": "안전관리 미종결과제 주간 인수인계표",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-PRA-22-10.xlsx",
        "forbidden_formula": False,
    },
    "REF-C002": {
        "source_title": "안전보건활동 목표/세부 추진계획",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-REF-C002.xlsx",
        "forbidden_formula": False,
    },
    "REF-C003": {
        "source_title": "위험기계·기구·설비 목록 작성 서식",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-REF-C003.xlsx",
        "forbidden_formula": False,
    },
    "REF-C004": {
        "source_title": "유해·위험물질 목록 작성 서식",
        "design_type": "CALC_AGG",
        "output_filename": "TAI-FORM-REF-C004.xlsx",
        "forbidden_formula": True,
    },
    "REF-C005": {
        "source_title": "작업별 위험과관리 대장",
        "design_type": "DATE_STATUS",
        "output_filename": "TAI-FORM-REF-C005.xlsx",
        "forbidden_formula": False,
    },
    "REF-C007": {
        "source_title": "안전보건예산 편성 서식",
        "design_type": "CALC_AGG",
        "output_filename": "TAI-FORM-REF-C007.xlsx",
        "forbidden_formula": False,
    },
    "REF-C008": {
        "source_title": "안전보건 전문이력 평가 기준 및 평가표",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-REF-C008.xlsx",
        "forbidden_formula": False,
    },
    "REF-C009": {
        "source_title": "안전보건 전문인력 등 배치표 및 담당업무",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-REF-C009.xlsx",
        "forbidden_formula": False,
    },
    "REF-C011": {
        "source_title": "도급·용역·위탁 업체 안전보건 수준 평가",
        "design_type": "CALC_AGG",
        "output_filename": "TAI-FORM-REF-C011.xlsx",
        "forbidden_formula": False,
    },
    "REF-C014": {
        "source_title": "재해 감소대책 수립 및 실행 계획서 작성 서식",
        "design_type": "DATE_STATUS",
        "output_filename": "TAI-FORM-REF-C014.xlsx",
        "forbidden_formula": False,
    },
    "REF-C016": {
        "source_title": "연간 안전보건교육 수립 서식",
        "design_type": "CALC_AGG",
        "output_filename": "TAI-FORM-REF-C016.xlsx",
        "forbidden_formula": False,
    },
    "REF-C022": {
        "source_title": "중량물 취급 작업계획서",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-REF-C022.xlsx",
        "forbidden_formula": False,
    },
    "REF-C023": {
        "source_title": "안전보호구 지급대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-REF-C023.xlsx",
        "forbidden_formula": False,
    },
    "REF-C026": {
        "source_title": "위험성평가 기록표(3단계 판단법)",
        "design_type": "DATE_STATUS",
        "output_filename": "TAI-FORM-REF-C026.xlsx",
        "forbidden_formula": False,
    },
    "REF-C027": {
        "source_title": "체크리스트형 위험성평가표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-REF-C027.xlsx",
        "forbidden_formula": False,
    },
    "REF-C028": {
        "source_title": "핵심요인 분석법(OPS) 위험성평가표",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-REF-C028.xlsx",
        "forbidden_formula": False,
    },
    "REF-C029": {
        "source_title": "빈도·강도법 위험성평가표",
        "design_type": "CALC_AGG",
        "output_filename": "TAI-FORM-REF-C029.xlsx",
        "forbidden_formula": True,
    },
    "REF-C031": {
        "source_title": "안전보건교육 실시일지",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-REF-C031.xlsx",
        "forbidden_formula": False,
    },
    "REF-C033": {
        "source_title": "도급업체 안전관리 이행점검표",
        "design_type": "DATE_STATUS",
        "output_filename": "TAI-FORM-REF-C033.xlsx",
        "forbidden_formula": False,
    },
    "REF-C037": {
        "source_title": "종사자 위험개선 건의·조치대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-REF-C037.xlsx",
        "forbidden_formula": False,
    },
    "REF-C038": {
        "source_title": "안전보건 관계법령 의무이행 점검표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-REF-C038.xlsx",
        "forbidden_formula": False,
    },
    "REF-C039": {
        "source_title": "사업장 화학물질 취급목록 관리대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-REF-C039.xlsx",
        "forbidden_formula": False,
    },
    "REF-C040": {
        "source_title": "제품별 MSDS 수령·개정 이력대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-REF-C040.xlsx",
        "forbidden_formula": False,
    },
    "REF-C041": {
        "source_title": "화학물질 경고표지 확인 점검표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-REF-C041.xlsx",
        "forbidden_formula": False,
    },
    "REF-C042": {
        "source_title": "화학물질 저장구역 점검표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-REF-C042.xlsx",
        "forbidden_formula": False,
    },
    "REF-C043": {
        "source_title": "화학물질 누출 비상대응 훈련기록",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-REF-C043.xlsx",
        "forbidden_formula": False,
    },
    "REF-C044": {
        "source_title": "MSDS 교육·주지 확인 기록",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-REF-C044.xlsx",
        "forbidden_formula": False,
    },
    "REF-C046": {
        "source_title": "소방시설 점검 후 보완조치 관리대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-REF-C046.xlsx",
        "forbidden_formula": False,
    },
    "REF-C047": {
        "source_title": "비상대피훈련 실시 및 개선기록",
        "design_type": "DOC_TABLE",
        "output_filename": "TAI-FORM-REF-C047.xlsx",
        "forbidden_formula": False,
    },
    "REF-C052": {
        "source_title": "전기설비 일상 점검기록표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-REF-C052.xlsx",
        "forbidden_formula": False,
    },
    "REF-C056": {
        "source_title": "승강기 고장·조치 이력대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-REF-C056.xlsx",
        "forbidden_formula": False,
    },
    "REF-C057": {
        "source_title": "고압가스 설비 점검관리대장",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-REF-C057.xlsx",
        "forbidden_formula": False,
    },
    "REF-C058": {
        "source_title": "고압가스 누출 비상대응 점검표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-REF-C058.xlsx",
        "forbidden_formula": False,
    },
    "REF-C065": {
        "source_title": "공종별 위험성평가 및 변경 이력표",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-REF-C065.xlsx",
        "forbidden_formula": False,
    },
    "REF-C067": {
        "source_title": "현장 일일 안전점검 기록표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-REF-C067.xlsx",
        "forbidden_formula": False,
    },
    "REF-C069": {
        "source_title": "작업환경측정 대상 유해인자 사전 조사표",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-REF-C069.xlsx",
        "forbidden_formula": False,
    },
    "REF-C070": {
        "source_title": "작업환경측정 결과 개선관리대장",
        "design_type": "DATE_STATUS",
        "output_filename": "TAI-FORM-REF-C070.xlsx",
        "forbidden_formula": False,
    },
    "REF-C071": {
        "source_title": "건강진단 일정·실시 관리대장",
        "design_type": "CALC_AGG",
        "output_filename": "TAI-FORM-REF-C071.xlsx",
        "forbidden_formula": False,
    },
    "REF-C073": {
        "source_title": "근골격계 부담작업 유해요인 개선관리표",
        "design_type": "DATE_STATUS",
        "output_filename": "TAI-FORM-REF-C073.xlsx",
        "forbidden_formula": False,
    },
    "RP-01": {
        "source_title": "설비 예방보전 일정·실적표",
        "design_type": "CALC_AGG",
        "output_filename": "TAI-FORM-RP-01.xlsx",
        "forbidden_formula": False,
    },
    "RP-03": {
        "source_title": "정비작업 위험확인·에너지격리 확인표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-RP-03.xlsx",
        "forbidden_formula": False,
    },
    "RP-04": {
        "source_title": "생산·보전 교대 인수인계 기록부",
        "design_type": "DAILY_LOG",
        "output_filename": "TAI-FORM-RP-04.xlsx",
        "forbidden_formula": False,
    },
    "RP-05": {
        "source_title": "설비 정지·재가동 승인기록",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-RP-05.xlsx",
        "forbidden_formula": False,
    },
    "RP-07": {
        "source_title": "작업환경·안전 개선과제 월간관리표",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-RP-07.xlsx",
        "forbidden_formula": False,
    },
    "RP-08": {
        "source_title": "시설·설비별 법정검사 일정관리표",
        "design_type": "DATE_STATUS",
        "output_filename": "TAI-FORM-RP-08.xlsx",
        "forbidden_formula": False,
    },
    "RP-09": {
        "source_title": "시설관리 일일 운영일지",
        "design_type": "DAILY_LOG",
        "output_filename": "TAI-FORM-RP-09.xlsx",
        "forbidden_formula": False,
    },
    "RP-11": {
        "source_title": "설비 하자·수리요청 및 처리대장",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-RP-11.xlsx",
        "forbidden_formula": False,
    },
    "RP-12": {
        "source_title": "시설 비상경보 발생·대응이력부",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-RP-12.xlsx",
        "forbidden_formula": False,
    },
    "RP-14": {
        "source_title": "연구실 옥외저장소 점검일지",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-RP-14.xlsx",
        "forbidden_formula": False,
    },
    "RP-15": {
        "source_title": "연구실 등록·변경·폐쇄 신청 확인표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-RP-15.xlsx",
        "forbidden_formula": False,
    },
    "RP-16": {
        "source_title": "연구실 교차점검 결과·분석보고서",
        "design_type": "PLAN_EVAL",
        "output_filename": "TAI-FORM-RP-16.xlsx",
        "forbidden_formula": False,
    },
    "RP-17": {
        "source_title": "연구실 안전교육 이수·보완 확인표",
        "design_type": "CHECKLIST",
        "output_filename": "TAI-FORM-RP-17.xlsx",
        "forbidden_formula": False,
    },
    "RP-22": {
        "source_title": "유효기간·용기상태 점검표",
        "design_type": "DATE_STATUS",
        "output_filename": "TAI-FORM-RP-22.xlsx",
        "forbidden_formula": False,
    },
    "RP-23": {
        "source_title": "화학폐기물 불출·인계 확인기록",
        "design_type": "CUMULATIVE",
        "output_filename": "TAI-FORM-RP-23.xlsx",
        "forbidden_formula": False,
    },
}
