"""Persona 정의 — 8개 Synthetic Runtime User 유형."""

PERSONAS = {
    "normal_operator": {
        "label": "\uc77c\ubc18 \uc6b4\uc601\uc790",
        "workflow_freq": 1.0,
        "retry_rate": 0.05,
        "timeout_rate": 0.02,
        "abandon_rate": 0.01,
        "burst_rate": 0.0,
        "working_hours": (9, 18),
        "degradation_sensitivity": 0.1,
    },
    "impatient_user": {
        "label": "\uc870\uae09\ud55c \uc0ac\uc6a9\uc790",
        "workflow_freq": 1.5,
        "retry_rate": 0.15,
        "timeout_rate": 0.08,
        "abandon_rate": 0.12,
        "burst_rate": 0.05,
        "working_hours": (8, 20),
        "degradation_sensitivity": 0.3,
    },
    "unstable_user": {
        "label": "\ubd88\uc548\uc815 \uc0ac\uc6a9\uc790",
        "workflow_freq": 0.8,
        "retry_rate": 0.2,
        "timeout_rate": 0.15,
        "abandon_rate": 0.08,
        "burst_rate": 0.1,
        "working_hours": (0, 24),
        "degradation_sensitivity": 0.5,
    },
    "large_enterprise": {
        "label": "\ub300\uae30\uc5c5",
        "workflow_freq": 3.0,
        "retry_rate": 0.03,
        "timeout_rate": 0.01,
        "abandon_rate": 0.005,
        "burst_rate": 0.15,
        "working_hours": (7, 22),
        "degradation_sensitivity": 0.05,
    },
    "night_shift": {
        "label": "\uc57c\uac04 \uc6b4\uc601\uc790",
        "workflow_freq": 0.6,
        "retry_rate": 0.1,
        "timeout_rate": 0.05,
        "abandon_rate": 0.03,
        "burst_rate": 0.02,
        "working_hours": (22, 6),
        "degradation_sensitivity": 0.2,
    },
    "flaky_client": {
        "label": "\ubd88\uc548\uc815 \ud074\ub77c\uc774\uc5b8\ud2b8",
        "workflow_freq": 0.7,
        "retry_rate": 0.25,
        "timeout_rate": 0.2,
        "abandon_rate": 0.15,
        "burst_rate": 0.08,
        "working_hours": (0, 24),
        "degradation_sensitivity": 0.6,
    },
    "burst_client": {
        "label": "\ubc84\uc2a4\ud2b8 \ud074\ub77c\uc774\uc5b8\ud2b8",
        "workflow_freq": 0.3,
        "retry_rate": 0.05,
        "timeout_rate": 0.03,
        "abandon_rate": 0.02,
        "burst_rate": 0.4,
        "working_hours": (9, 18),
        "degradation_sensitivity": 0.1,
    },
    "abandoned_flow_user": {
        "label": "\uc911\ub3c4 \ud3ec\uae30 \uc0ac\uc6a9\uc790",
        "workflow_freq": 0.5,
        "retry_rate": 0.02,
        "timeout_rate": 0.1,
        "abandon_rate": 0.35,
        "burst_rate": 0.0,
        "working_hours": (10, 16),
        "degradation_sensitivity": 0.4,
    },
}

# Tenant → Persona 매핑 (20개 tenant)
TENANT_PERSONAS = {
    "mock_stable_01": "normal_operator",
    "mock_stable_02": "normal_operator",
    "mock_stable_03": "normal_operator",
    "mock_enterprise_01": "large_enterprise",
    "mock_enterprise_02": "large_enterprise",
    "mock_enterprise_03": "large_enterprise",
    "mock_impatient_01": "impatient_user",
    "mock_impatient_02": "impatient_user",
    "mock_unstable_01": "unstable_user",
    "mock_unstable_02": "unstable_user",
    "mock_night_01": "night_shift",
    "mock_night_02": "night_shift",
    "mock_flaky_01": "flaky_client",
    "mock_flaky_02": "flaky_client",
    "mock_flaky_03": "flaky_client",
    "mock_burst_01": "burst_client",
    "mock_burst_02": "burst_client",
    "mock_abandon_01": "abandoned_flow_user",
    "mock_abandon_02": "abandoned_flow_user",
    "mock_growing_01": "normal_operator",
}
