"""OBJ-CHEM official KOSHA MSDS OpenAPI contract. CHEM-02.

Search results are candidates, not identity.
"""
from __future__ import annotations

SOURCE_ID = "KOSHA_MSDS"
SOURCE_CONTRACT_VERSION = "KOSHA_MSDS_OPENAPI_V1"
DATASET_ID = "15157612"
DATASET_URL = "https://www.data.go.kr/data/15157612/openapi.do"
PROVIDER = "한국산업안전보건공단"
BASE_HOST_PATH = "apis.data.go.kr/B552468/msdschem"
BASE_URL = "https://apis.data.go.kr/B552468/msdschem"
LIST_OPERATION = "getChemList"
DETAIL_OPERATION_PREFIX = "getChemDetail"
CONTENT_ID_PREFIX = "CHEM:"
LICENSE = "이용허락범위 제한 없음"
ROLE = "PUBLIC_REFERENCE_CHEMICAL_KNOWLEDGE"

SUCCESS_RESULT_CODES = frozenset({"00"})
RATE_LIMIT_DAILY_CODES = frozenset({"22"})
RATE_LIMIT_SECOND_CODES = frozenset({"23"})

SEARCH_CND_KOREAN_NAME = 0
SEARCH_CND_CAS = 1
SEARCH_CND_UN = 2
SEARCH_CND_KE = 3
SEARCH_CND_EN = 4
ALLOWED_SEARCH_CND = frozenset({0, 1, 2, 3, 4})

SECTION_MIN = 1
SECTION_MAX = 16
ALLOWED_SECTIONS = tuple(range(SECTION_MIN, SECTION_MAX + 1))

LIST_IDENTITY_FIELDS = (
    "chemId",
    "chemNameKor",
    "casNo",
    "keNo",
    "enNo",
    "unNo",
    "lastDate",
    "openYn",
    "koshaConfirm",
)

ENUMERATION_PROBE = "PROBE"
ENUMERATION_BOUNDED_SEARCH = "BOUNDED_SEARCH"
ENUMERATION_FULL_OFFICIAL = "FULL_OFFICIAL"
CHEM02_ALLOWED_ENUMERATION = frozenset({ENUMERATION_PROBE})

SNAPSHOT_RUNNING = "RUNNING"
SNAPSHOT_COMPLETED = "COMPLETED"
SNAPSHOT_FAILED = "FAILED"

PUBLISH_NOT_PUBLISHED = "NOT_PUBLISHED"
PUBLISH_PUBLISHED_FULL = "PUBLISHED_FULL"

IDENTITY_READY = "READY"
IDENTITY_HOLD = "HOLD"

DETAIL_COMPLETE = "COMPLETE"
DETAIL_INCOMPLETE = "INCOMPLETE"
DETAIL_EMPTY_BUT_VALID = "EMPTY_BUT_VALID"

DEFAULT_TIMEOUT_SECONDS = 30
DEFAULT_MAX_ATTEMPTS = 3
DEFAULT_NUM_OF_ROWS = 10
MAX_NUM_OF_ROWS = 1000
# CHEM-01 search accepted 10/100/1000. Not an official maximum.
WORKING_PAGE_SIZE = 1000

# Official HWP: getChemList is a search list, not a dump-all.
LIST_PURPOSE = "화학물질 검색 목록 조회"
OPENAPI_LIST_CONTRACT = "SEARCH-ONLY"
SEARCH_WRD_REQUIRED = True
SEARCH_CND_REQUIRED = True
TOTAL_COUNT_SEMANTICS = "SEARCH_RESULT_COUNT"
DOCUMENTED_OPENAPI_FULL_ENUMERATION = "NO"
DOCUMENTED_FULL_ENUMERATION_API = "NOT_AVAILABLE"
API_FULL_ENUMERATION = "BLOCKED_BY_SOURCE_CONTRACT"
INITIAL_FULL_SEED = "BLOCKED"
# Historical alias of API_FULL_ENUMERATION. Not an outage.
FULL_LIST_API = API_FULL_ENUMERATION
FULL_LIST_MEASURED_TOTAL_COUNT = 0

SEED_KOSHA_OFFICIAL_FULL_LIST = "KOSHA_OFFICIAL_FULL_LIST"
SEED_DATA_GO_KR_FILE_DATASET = "DATA_GO_KR_FILE_DATASET"
SEED_KOSHA_OFFICIAL_BULK_INDEX = "KOSHA_OFFICIAL_BULK_INDEX"
SEED_FUTURE_ENUMERATION_API = "FUTURE_ENUMERATION_API"
OFFICIAL_SEED_SOURCES = frozenset(
    {
        SEED_KOSHA_OFFICIAL_FULL_LIST,
        SEED_DATA_GO_KR_FILE_DATASET,
        SEED_KOSHA_OFFICIAL_BULK_INDEX,
        SEED_FUTURE_ENUMERATION_API,
    }
)

REMOVED_CANDIDATE = "REMOVED_CANDIDATE"
DIFF_NEW = "NEW"
DIFF_CHANGED = "CHANGED"
DIFF_UNCHANGED = "UNCHANGED"

CHEM04_ALLOWED_ENUMERATION = frozenset(
    {ENUMERATION_PROBE, ENUMERATION_BOUNDED_SEARCH, ENUMERATION_FULL_OFFICIAL}
)

SERVICE_KEY_ENV = (
    "DATA_GO_KR_SERVICE_KEY",
    "KOSHA_SERVICE_KEY",
    "BUILDING_API_KEY",
)
