"""OBJ-CHEM official KOSHA MSDS OpenAPI contract. CHEM-02.

Search results are candidates, not identity.
"""
from __future__ import annotations

SOURCE_ID = "KOSHA_MSDS"
# WO-CHEM-04-API-V12-ALIGN-001: aligned to official spec v1.2 (2026-09-16).
# Change summary from spec cover page: "호출URL 현행화, 활용방법 추가".
SOURCE_CONTRACT_VERSION = "KOSHA_MSDS_OPENAPI_V1_2"
OFFICIAL_SPEC_VERSION = "1.2"
OFFICIAL_SPEC_DATE = "2026-09-16"
DATASET_ID = "15157612"
DATASET_URL = "https://www.data.go.kr/data/15157612/openapi.do"
PROVIDER = "한국산업안전보건공단"
BASE_HOST_PATH = "apis.data.go.kr/B552468/msdschem1"
BASE_URL = "https://apis.data.go.kr/B552468/msdschem1"
LIST_OPERATION = "getChemList001"
# Under spec v1.2 every operation now ends in a trailing '1'. The section
# number is zero-padded to 2 digits, then a literal '1' is appended:
#   Detail 01 → getChemDetail011
#   Detail 09 → getChemDetail091
#   Detail 10 → getChemDetail101
#   Detail 16 → getChemDetail161
# The old bare prefix ("getChemDetail") is retained ONLY for historical
# reference in errors that quote pre-v1.2 evidence. All new construction
# must go through DETAIL_OPERATION_TEMPLATE / detail_operation().
DETAIL_OPERATION_PREFIX = "getChemDetail"
DETAIL_OPERATION_TEMPLATE = "getChemDetail{section:02d}1"
CONTENT_ID_PREFIX = "CHEM:"
LICENSE = "이용허락범위 제한 없음"
ROLE = "PUBLIC_REFERENCE_CHEMICAL_KNOWLEDGE"

SUCCESS_RESULT_CODES = frozenset({"00"})
RATE_LIMIT_DAILY_CODES = frozenset({"22"})
RATE_LIMIT_SECOND_CODES = frozenset({"23"})

SEARCH_CND_KOREAN_NAME = 0
SEARCH_CND_CAS = 1
SEARCH_CND_UN = 2
SEARCH_CND_KE = 3
SEARCH_CND_EN = 4
ALLOWED_SEARCH_CND = frozenset({0, 1, 2, 3, 4})

SECTION_MIN = 1
SECTION_MAX = 16
ALLOWED_SECTIONS = tuple(range(SECTION_MIN, SECTION_MAX + 1))


def detail_operation(section: int) -> str:
    """v1.2 operation name for a given Detail section (1..16).

    Under spec v1.2:
      Detail 01 → getChemDetail011
      Detail 09 → getChemDetail091
      Detail 10 → getChemDetail101
      Detail 16 → getChemDetail161
    """
    n = int(section)
    if not (SECTION_MIN <= n <= SECTION_MAX):
        raise ValueError(
            f"section must be {SECTION_MIN}..{SECTION_MAX}, got {n}"
        )
    return DETAIL_OPERATION_TEMPLATE.format(section=n)


DISCOVERY_SECTION = 1

LIST_IDENTITY_FIELDS = (
    "chemId",
    "chemNameKor",
    "casNo",
    "keNo",
    "enNo",
    "unNo",
    "lastDate",
    "openYn",
    "koshaConfirm",
)

ENUMERATION_PROBE = "PROBE"
ENUMERATION_BOUNDED_SEARCH = "BOUNDED_SEARCH"
ENUMERATION_FULL_OFFICIAL = "FULL_OFFICIAL"
CHEM02_ALLOWED_ENUMERATION = frozenset({ENUMERATION_PROBE})

SNAPSHOT_RUNNING = "RUNNING"
SNAPSHOT_COMPLETED = "COMPLETED"
SNAPSHOT_FAILED = "FAILED"

PUBLISH_NOT_PUBLISHED = "NOT_PUBLISHED"
PUBLISH_PUBLISHED_FULL = "PUBLISHED_FULL"

IDENTITY_READY = "READY"
IDENTITY_HOLD = "HOLD"

DETAIL_COMPLETE = "COMPLETE"
DETAIL_INCOMPLETE = "INCOMPLETE"
DETAIL_EMPTY_BUT_VALID = "EMPTY_BUT_VALID"

DEFAULT_TIMEOUT_SECONDS = 30
DEFAULT_MAX_ATTEMPTS = 3
DEFAULT_NUM_OF_ROWS = 10
MAX_NUM_OF_ROWS = 1000
# CHEM-01 search accepted 10/100/1000. Not an official maximum.
WORKING_PAGE_SIZE = 1000

# Official HWP: getChemList is a search list, not a dump-all.
LIST_PURPOSE = "화학물질 검색 목록 조회"
OPENAPI_LIST_CONTRACT = "SEARCH-ONLY"
SEARCH_WRD_REQUIRED = True
SEARCH_CND_REQUIRED = True
TOTAL_COUNT_SEMANTICS = "SEARCH_RESULT_COUNT"
DOCUMENTED_OPENAPI_FULL_ENUMERATION = "NO"
DOCUMENTED_FULL_ENUMERATION_API = "NOT_AVAILABLE"
API_FULL_ENUMERATION = "BLOCKED_BY_SOURCE_CONTRACT"
INITIAL_FULL_SEED = "BLOCKED"
# Historical alias of API_FULL_ENUMERATION. Not an outage.
FULL_LIST_API = API_FULL_ENUMERATION
FULL_LIST_MEASURED_TOTAL_COUNT = 0

# PATCH-3 empirical Detail01 identity discovery. Not a documented enumeration API.
DISCOVERY_METHOD = "DETAIL01_ID_DISCOVERY"
EMPIRICAL_API_CENSUS = "EMPIRICAL_API_CENSUS"
DISCOVERY_OPERATION = detail_operation(DISCOVERY_SECTION)
DISCOVERY_DISCOVERED = "DISCOVERED"
DISCOVERY_ABSENT = "ABSENT"
DISCOVERY_UNKNOWN = "UNKNOWN"
CHEM_ID_WIDTH = 6
DISCOVERY_RANGE_START = 1
DISCOVERY_RANGE_END = 50000
DISCOVERY_TAIL_BLOCK = 10000
DISCOVERY_STAGES = (
    (1, 100),
    (101, 1000),
    (1001, 5000),
    (5001, 50000),
)
DISCOVERY_WORKERS_START = 4
DISCOVERY_WORKERS_MAX = 8
PORTAL_DISPLAYED_DAILY_QUOTA = 1000
PORTAL_QUOTA_STATUS = "ADVISORY"
RUNTIME_API_RESPONSE = "EXECUTION_TRUTH"
INITIAL_SEED_CANDIDATE_PASS = "PASS"
INITIAL_SEED_CANDIDATE_CONDITIONAL = "CONDITIONAL"
INITIAL_SEED_CANDIDATE_BLOCKED = "BLOCKED"
QUOTA_MESSAGE_MARKERS = (
    "service request limit exceeded",
    "daily request limit",
    "gateway throttling",
    "limited number of service requests exceeds",
)

# PATCH-4: sequential Detail01 scan is fallback only. Official current index is primary.
DISCOVERY_PRIMARY_ENUMERATION = False
DISCOVERY_ROLE = "FALLBACK_VALIDATION"
SECONDARY_BOOTSTRAP_SOURCE = "Yuyongkim/inconvenience-msds"
SECONDARY_BOOTSTRAP_DATASET = "Yuyongkim/inconvenience-msds"
SECONDARY_HF_REVISION = "5db49df655360dc69cc250ecb41058bf464553fa"
SECONDARY_HF_TRAIN_URL = (
    "https://huggingface.co/datasets/Yuyongkim/inconvenience-msds/resolve/"
    "5db49df655360dc69cc250ecb41058bf464553fa/train.jsonl"
)
SECONDARY_HF_TRAIN_SHA256 = "2c342e638e403540076f0e0d13d0018f7671b11747b5a40cb67a5245d13a4227"
SECONDARY_HF_TRAIN_BYTES = 882524767
SECONDARY_GITHUB_HEAD = "f98915d4d1a89a90083e7b70914cdb1b49e14ccf"
SECONDARY_CONTENT_PRODUCTION_INGEST = "NO"
CURSOR_FULL_DATA_EXECUTION = False
LOCAL_FULL_DATA_EXECUTION = True
PRODUCTION_INGEST_UNTIL_GPT_APPROVAL = False
SECONDARY_CONTENT_PRODUCTION_PUBLICATION = "NO"
OBSERVED_SECONDARY_CONTENT_FIELDS = (
    "chem_id",
    "name_ko",
    "cas_no",
    "name_en",
    "sections",
    "total_text_chars",
    "total_braille_chars",
)
OBSERVED_SECONDARY_SECTION_FIELDS = ("section_no", "title", "text_ko", "braille")
ABSENT_SECONDARY_CONTENT_FIELDS = (
    "lastDate",
    "last_date",
    "openYn",
    "revision",
    "snapshot",
    "source_url",
    "retrieved_at",
    "content_hash",
)
SECTION_PRESENT = "PRESENT"
SECTION_EMPTY = "EMPTY"
SECTION_MISSING = "MISSING"
SECTION_INVALID = "INVALID"
CONTENT_SECONDARY_COMPLETE = "SECONDARY_COMPLETE"
CONTENT_SECONDARY_PARTIAL = "SECONDARY_PARTIAL"
CONTENT_SECONDARY_EMPTY_VALID = "SECONDARY_EMPTY_VALID"
CONTENT_SECONDARY_INVALID = "SECONDARY_INVALID"
CONTENT_SECONDARY_MISSING = "SECONDARY_MISSING"
FRESHNESS_CURRENT_MATCH = "CURRENT_MATCH"
FRESHNESS_CURRENT_CHANGED = "CURRENT_CHANGED"
FRESHNESS_DATE_UNKNOWN = "DATE_UNKNOWN"
REASON_OFFICIAL_ONLY = "OFFICIAL_ONLY"
REASON_SECONDARY_MISSING_SECTION = "SECONDARY_MISSING_SECTION"
REASON_SECONDARY_INVALID_SECTION = "SECONDARY_INVALID_SECTION"
REASON_REVISION_CHANGED = "REVISION_CHANGED"
REASON_REVISION_UNKNOWN = "REVISION_UNKNOWN"
REASON_SECONDARY_COMPLETE_CANDIDATE = "SECONDARY_COMPLETE_CANDIDATE"
REASON_SECONDARY_EMPTY_VALID = "SECONDARY_EMPTY_VALID"
# Presence + canonical hash use Korean MSDS body only. Braille is observed on
# secondary records but is out of TAI content-audit scope (not production content).
CONTENT_AUDIT_TEXT_FIELDS = ("text_ko", "textKo")
BRAILLE_IN_CONTENT_AUDIT = False
QUEUE_STRUCTURAL_DELTA = "STRUCTURAL_DELTA"
QUEUE_AUTHORITATIVE_VERIFY = "AUTHORITATIVE_VERIFY"
DETAIL01_OBSERVED_DAILY_STOP = 1000
DETAIL01_QUOTA_STATUS = "OBSERVED_NOT_PER_ENDPOINT_FACT"
MATCH_DIRECT_OFFICIAL_ID = "DIRECT_OFFICIAL_ID"
MATCH_CAS_EXACT = "CAS_EXACT"
MATCH_NAME_EXACT = "NAME_EXACT"
MATCH_COMPOUND_EXACT = "COMPOUND_EXACT"
MATCH_UNMATCHED = "UNMATCHED"
MATCH_AMBIGUOUS = "AMBIGUOUS"
API_VALIDATION_MAX_CALLS = 100
KOSHA_WEB_LIST_PATH = "/MSDSInfo/mgr/hub/chemList.do"
KOSHA_WEB_HOST = "https://msds.kosha.or.kr"
KOSHA_WEB_LIST_TYPE = "msds"
KOSHA_WEB_WORKERS = 1
DIFF_NEW_CURRENT = "NEW_CURRENT"
DIFF_REMOVED_CURRENT = "REMOVED_CURRENT"
DIFF_REVISION_CHANGED = "REVISION_CHANGED"
DIFF_UNCHANGED_CURRENT = "UNCHANGED"

SEED_KOSHA_OFFICIAL_FULL_LIST = "KOSHA_OFFICIAL_FULL_LIST"
SEED_DATA_GO_KR_FILE_DATASET = "DATA_GO_KR_FILE_DATASET"
SEED_KOSHA_OFFICIAL_BULK_INDEX = "KOSHA_OFFICIAL_BULK_INDEX"
SEED_FUTURE_ENUMERATION_API = "FUTURE_ENUMERATION_API"
OFFICIAL_SEED_SOURCES = frozenset(
    {
        SEED_KOSHA_OFFICIAL_FULL_LIST,
        SEED_DATA_GO_KR_FILE_DATASET,
        SEED_KOSHA_OFFICIAL_BULK_INDEX,
        SEED_FUTURE_ENUMERATION_API,
    }
)

REMOVED_CANDIDATE = "REMOVED_CANDIDATE"
DIFF_NEW = "NEW"
DIFF_CHANGED = "CHANGED"
DIFF_UNCHANGED = "UNCHANGED"

CHEM04_ALLOWED_ENUMERATION = frozenset(
    {ENUMERATION_PROBE, ENUMERATION_BOUNDED_SEARCH, ENUMERATION_FULL_OFFICIAL}
)

SERVICE_KEY_ENV = (
    "DATA_GO_KR_SERVICE_KEY",
    "KOSHA_SERVICE_KEY",
    "BUILDING_API_KEY",
)
LIVE_SAMPLE_KEY_ENV = (
    "KOSHA_SERVICE_KEY",
    "DATA_GO_KR_SERVICE_KEY",
)
EXPECTED_OPTIONC_SAMPLE_SHA256 = "b404725ade87b289e124abcca0652e91ec4bace1f5094d79f251860035af2351"
LIVE_SAMPLE_MAX_CALLS = 256
LIVE_SAMPLE_HARD_CAP = 320
LIVE_SAMPLE_RETRY_MAX = 2
CURSOR_LIVE_SAMPLE_MAX_CHEMS = 1
PREFLIGHT_CHEM_ID = "001008"
PREFLIGHT_SECTION = 1
FETCH_ERROR_PARSE = "PARSE"
FETCH_ERROR_TIMEOUT = "TIMEOUT"
FETCH_ERROR_TRANSPORT = "TRANSPORT"
