-- menu_catalog: safe nav 카탈로그. menu_code = route slug = role_menu_permissions.menu_code
CREATE TABLE IF NOT EXISTS public.menu_catalog (
  menu_code   text PRIMARY KEY,
  title       text NOT NULL,
  group_code  text NOT NULL,
  group_title text NOT NULL,
  sort_order  integer NOT NULL,
  sectors     text[] NOT NULL DEFAULT '{}',
  is_active   boolean NOT NULL DEFAULT true
);

INSERT INTO public.menu_catalog (menu_code, title, group_code, group_title, sort_order, sectors) VALUES
  ('safety-dashboard', '대시보드', 'DASHBOARD', '대시보드', 10, '{}'),
  ('my-company', '회사정보', 'FACILITY', '시설관리', 100, '{FACILITY,INDUSTRIAL}'),
  ('factory-list', '시설목록', 'FACILITY', '시설관리', 110, '{FACILITY,INDUSTRIAL}'),
  ('process-select', '공정관리', 'FACILITY', '시설관리', 120, '{INDUSTRIAL}'),
  ('my-equipment', '설비관리', 'FACILITY', '시설관리', 130, '{FACILITY,INDUSTRIAL}'),
  ('inspection-anchor', '점검항목관리', 'INSPECTION', '점검관리', 200, '{FACILITY,INDUSTRIAL}'),
  ('my-inspection', '점검목록', 'INSPECTION', '점검관리', 210, '{FACILITY,INDUSTRIAL}'),
  ('construction-work-list', '작업근로자', 'INSPECTION', '점검관리', 220, '{}'),
  ('inspection-calendar', '점검 캘린더', 'INSPECTION', '점검관리', 230, '{FACILITY,INDUSTRIAL}'),
  ('work-schedule-list', '업무일정', 'INSPECTION', '점검관리', 240, '{FACILITY,INDUSTRIAL}'),
  ('risk-assessment-list', '평가 목록', 'RISK', '위험성평가', 300, '{}'),
  ('risk-assessment-scale', '평가 척도 설정', 'RISK', '위험성평가', 310, '{}'),
  ('holiday-calendar', '휴무 캘린더', 'RISK', '위험성평가', 320, '{}'),
  ('risk-assessment-report', '중처법 반기 증적', 'RISK', '위험성평가', 330, '{}'),
  ('org-setting', '부서·팀·그룹', 'ORG', '조직 관리', 400, '{}'),
  ('worker-list', '작업근로자', 'ORG', '조직 관리', 410, '{INDUSTRIAL,CONSTRUCTION}'),
  ('construction-worker-list', '출입관리', 'ORG', '조직 관리', 420, '{CONSTRUCTION}'),
  ('manager-permission', '권한설정', 'ORG', '조직 관리', 430, '{INDUSTRIAL,CONSTRUCTION}'),
  ('tbm-list', 'TBM관리', 'TBM', 'TBM관리', 500, '{}'),
  ('safety-meeting-list', '안전회의', 'TBM', 'TBM관리', 510, '{}'),
  ('tbm-setting', 'TBM설정', 'TBM', 'TBM관리', 520, '{}'),
  ('education-list', '교육목록', 'EDUCATION', '교육관리', 600, '{}'),
  ('education-setting', '교육설정', 'EDUCATION', '교육관리', 610, '{}'),
  ('engine-schedule', '일정관리', 'DOCUMENT', '문서관리', 700, '{}'),
  ('engine-document', '엔진문서', 'DOCUMENT', '문서관리', 710, '{}'),
  ('document-forms', '서식작성', 'DOCUMENT', '문서관리', 720, '{}'),
  ('compliance-report', '증빙 리포트', 'DOCUMENT', '문서관리', 730, '{}'),
  ('notification-list', '알림센터', 'NOTIFICATION', '알림센터', 800, '{}'),
  ('my-contract', '결제내역', 'MYPAGE', '마이페이지', 900, '{}'),
  ('contact', '문의하기', 'MYPAGE', '마이페이지', 910, '{}'),
  ('safety-info', '안전정보', 'ETC', '기타', 1000, '{}'),
  ('equipment-qr-manager', 'QR/RFID 설비관리', 'ETC', '기타', 1010, '{}'),
  ('construction-site-list', '건설현장목록', 'ETC', '기타', 1020, '{CONSTRUCTION}'),
  ('construction-subcontractor-list', '하도급관리', 'ETC', '기타', 1025, '{CONSTRUCTION}'),
  ('construction-process-list', '건설공정목록', 'ETC', '기타', 1030, '{CONSTRUCTION}'),
  ('construction-inspection-list', '건설점검목록', 'ETC', '기타', 1040, '{CONSTRUCTION}'),
  ('construction-inspection-anchor', '건설 점검항목관리', 'ETC', '기타', 1050, '{CONSTRUCTION}'),
  ('inspection-custom', '맞춤점검', 'ETC', '기타', 1060, '{}'),
  ('my-diagnosis', '내 진단내역', 'ETC', '기타', 1070, '{}'),
  ('diagnosis-step1', '진단 1단계(업종선택)', 'ETC', '기타', 1080, '{}'),
  ('construction-step1', '건설 진단 1단계', 'ETC', '기타', 1090, '{CONSTRUCTION}')
ON CONFLICT (menu_code) DO UPDATE
  SET title = EXCLUDED.title,
      group_code = EXCLUDED.group_code,
      group_title = EXCLUDED.group_title,
      sort_order = EXCLUDED.sort_order,
      sectors = EXCLUDED.sectors,
      is_active = true;
