ALTER TABLE inspection_master
  ADD COLUMN IF NOT EXISTS sector VARCHAR(50),
  ADD COLUMN IF NOT EXISTS check_type VARCHAR(20) DEFAULT 'BOOLEAN',
  ADD COLUMN IF NOT EXISTS risk_type VARCHAR(30),
  ADD COLUMN IF NOT EXISTS pass_description TEXT,
  ADD COLUMN IF NOT EXISTS fail_action TEXT,
  ADD COLUMN IF NOT EXISTS related_service TEXT,
  ADD COLUMN IF NOT EXISTS is_mandatory BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS threshold_value TEXT,
  ADD COLUMN IF NOT EXISTS threshold_operator VARCHAR(10),
  ADD COLUMN IF NOT EXISTS unit VARCHAR(20);

ALTER TABLE inspection_set_items
  ADD COLUMN IF NOT EXISTS check_type VARCHAR(20) DEFAULT 'BOOLEAN',
  ADD COLUMN IF NOT EXISTS risk_type VARCHAR(30),
  ADD COLUMN IF NOT EXISTS pass_description TEXT,
  ADD COLUMN IF NOT EXISTS fail_action TEXT,
  ADD COLUMN IF NOT EXISTS source VARCHAR(20) DEFAULT 'MANUAL',
  ADD COLUMN IF NOT EXISTS master_item_id UUID REFERENCES inspection_master(id),
  ADD COLUMN IF NOT EXISTS threshold_value TEXT,
  ADD COLUMN IF NOT EXISTS unit VARCHAR(20),
  ADD COLUMN IF NOT EXISTS check_method VARCHAR(20);
